Wildlife/Models/Contact.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace DeveloperWeb.Models
{
    public class Contact
    {
        [Required(ErrorMessageResourceName = "NameRequired", ErrorMessageResourceType = typeof(Resources.ContactUs.Contact))]
        [StringLength(200, MinimumLength = 2, ErrorMessageResourceName = "NameMax", ErrorMessageResourceType = typeof(Resources.ContactUs.Contact))]
        public string Name { get; set; }

        [StringLength(20, MinimumLength = 0, ErrorMessageResourceName = "PhoneMax", ErrorMessageResourceType = typeof(Resources.ContactUs.Contact))]
        public string Phone { get; set; }

        [Required(ErrorMessageResourceName = "EmailRequired", ErrorMessageResourceType = typeof(Resources.ContactUs.Contact))]
        [StringLength(200, MinimumLength = 2, ErrorMessageResourceName = "EmailMax", ErrorMessageResourceType = typeof(Resources.ContactUs.Contact))]
        [RegularExpression(@"^[a-zA-Z0-9._%+-]{1,64}@(?:[a-zA-Z0-9-]{1,63}\.){1,125}[a-zA-Z]{2,63}$", ErrorMessageResourceName = "EmailInvalid", ErrorMessageResourceType = typeof(Resources.ContactUs.Contact))]
        public string Email { get; set; }

        [Required(ErrorMessageResourceName = "MessageRequired", ErrorMessageResourceType = typeof(Resources.ContactUs.Contact))]
        public string Message { get; set; }

        public Contact() { }

        public bool SendEmail()
        {
            bool bRet = false;
            var fromName = Resources.WebsiteVariables.EmailFromName;
            var fromEmail = Resources.WebsiteVariables.EmailFromEmail;

            string strIp = System.Web.HttpContext.Current.Request.ServerVariables["REMOTE_ADDR"].ToString();
            string strRef = System.Web.HttpContext.Current.Request.UrlReferrer.Host;

            List<EmailParameter> ep = new List<EmailParameter>{
                new EmailParameter("NAME", Name),
                new EmailParameter("PHONE", Phone),
                new EmailParameter("EMAIL", Email),
                new EmailParameter("MESSAGE", Message),
                new EmailParameter("IP", strIp),
                new EmailParameter("REFERRER",strRef)
                };

            int r1 = new EmailServer().EmailSend("EmailContact", new MailType(fromEmail), ep, null);
            bRet = r1 >= 0 ? true : false;

            return bRet;
        }
    }
}

Wildlife/Models/EducationWork.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Models
{
    public class EducationWorkVM // ViewModel
    {
        //public IEnumerable<Education> Educations { get; set; }
        //public IEnumerable<Work> Works { get; set; }
    }
}

Wildlife/Models/Slide.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Models
{
    public class Slide
    {
        public int Id { get; set; }
        public string  Large { get; set; }
        public string Small { get; set; }

        public Slide() { }
        public Slide(int id, string large, string small)
        {
            Id = id;
            Large = large;
            Small = small;
        }

        public List<Slide> GetList()
        {
            var items = new List<Slide>();
            int i = 1;
            bool bOk = true;

            var rm = Resources.Slider.ResourceManager;
            while (bOk)
            {
                try
                {
                    var name = rm.GetString("slide" + i + "Large");
                    if (name == null) bOk = false;
                    else
                    {
                        items.Add(new Slide(i, name
                            , rm.GetString("slide" + i + "Small"))
                            );
                    }
                    i++;
                }
                catch (Exception)
                {
                    bOk = false;
                }
            }
            return items;
        }


    }
}

Wildlife/Controllers/ContactUsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Threading.Tasks;

namespace DeveloperWeb.Controllers
{
    public class ContactUsController : Controller
    {
        // GET: ContactUs
        public ActionResult Index()
        {
            return PartialView();
        }

        public ActionResult ContactResult()
        {
            return PartialView();
        }

        public ActionResult ContactAjax()
        {
            var contact = new Models.Contact();
            /*contact.Message = Resources.ContactUs.Contact.MessagePlaceholder;
            contact.Name = Resources.ContactUs.Contact.NamePlaceholder;
            contact.Phone= Resources.ContactUs.Contact.PhonePlaceholder;
            contact.Email = Resources.ContactUs.Contact.EmailPlaceholder;
            */
            return PartialView(contact);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> ContactAjax(Models.Contact task)
        {
            if (ModelState.IsValid)
            {
                var data1 = task.Name + ", " + task.Email;

                var bRet = task.SendEmail();
                TempData["Status"] = "emailSent";

                return PartialView("contactResult", task);
            }
            else
            {
                TempData["Status"] = "Message err from controller";
                return PartialView("ContactAjax", task);
                //return PartialView("contactResult", task);
            }
        }

    }
}

Wildlife/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            //ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            //ViewBag.Message = "Your contact page.";

            return View();
        }
        public ActionResult Education()
        {
            var eduw = new Models.EducationWorkVM()
            {
                //Educations = new Models.Education().GetList(),
                //Works = new Models.Work().GetList()
            };
            return PartialView(eduw);
        }
        public ActionResult Slider()
        {
            var items = new Models.Slide().GetList();
            return PartialView("Slider", items);
        }
        public ActionResult Base64Encode()
        {
            var qs = Utils.Rq("c");
            var retV = Utils.Base64Encode(qs);
            Log.AddLogEntry("-" + retV);
            return PartialView("Error");
        }
        public ActionResult Base64Decode()
        {
            var qs = Utils.Rq("c");
            var retV = Utils.Base64Decode(qs);
            Log.AddLogEntry("-"+retV);
            return PartialView("Error");
        }

    }
}

Wildlife/Views/ContactUs/ContactAjax.cshtml
@model DeveloperWeb.Models.Contact
<!-- contact -->
<div class="contact-form-wthreelayouts register-wthree" id="contactdiv">
        @if (TempData["Status"] != null)
        {
            <div class="alert-info alert" style="display:none;">@TempData["Status"]</div>
        }
        @Html.ValidationSummary(false, Resources.Error.summary, new { @class = "validate" })

        @{
            var culture = System.Threading.Thread.CurrentThread.CurrentUICulture.Name.ToLowerInvariant();
            var options = new AjaxOptions()
            {
                HttpMethod = "Post",
                InsertionMode = InsertionMode.ReplaceWith,
                UpdateTargetId = "contactdiv"
            };
        }
        @using (Ajax.BeginForm("ContactAjax", "ContactUs", new { language = culture }, options))
        {
            @Html.AntiForgeryToken()
            <div class="form-group">
                @Html.LabelFor(x => x.Name, Resources.ContactUs.Contact.NameHead)
                @Html.TextBoxFor(x => x.Name, new { @class = "form-control", @placeholder = @Resources.ContactUs.Contact.NamePlaceholder, onfocus = "if (this.value == '" + Resources.ContactUs.Contact.NamePlaceholder + "') this.value = '';", onblur = "if (this.value == '') { this.value = '" + Resources.ContactUs.Contact.NamePlaceholder + "'; }" })
                @Html.ValidationMessageFor(x => x.Name, null, new { @class = "validate" })
            </div>
            <div class="form-group">
                @Html.LabelFor(x => x.Phone, Resources.ContactUs.Contact.PhoneHead)
                @Html.TextBoxFor(x => x.Phone, new { @class = "form-control", @placeholder = @Resources.ContactUs.Contact.PhonePlaceholder, onfocus = "if (this.value == '" + Resources.ContactUs.Contact.PhonePlaceholder + "') this.value = '';", onblur = "if (this.value == '') { this.value = '" + Resources.ContactUs.Contact.PhonePlaceholder + "'; }" })
                @Html.ValidationMessageFor(x => x.Phone, null, new { @class = "validate" })
            </div>
            <div class="form-group">
                @Html.LabelFor(x => x.Email, Resources.ContactUs.Contact.EmailHead)
                @Html.TextBoxFor(x => x.Email, new { @class = "form-control", @placeholder = @Resources.ContactUs.Contact.EmailPlaceholder, onfocus = "if (this.value == '" + Resources.ContactUs.Contact.EmailPlaceholder + "') this.value = '';", onblur = "if (this.value == '') { this.value = '" + @Resources.ContactUs.Contact.EmailPlaceholder+ "'; }" })
                @Html.ValidationMessageFor(x => x.Email, null, new { @class = "validate" })
            </div>
            <div class="form-group">
                @Html.LabelFor(x=> x.Message, Resources.ContactUs.Contact.MessageHead)
                @Html.TextAreaFor(x => x.Message, new { @class = "form-control", @placeholder = @Resources.ContactUs.Contact.MessagePlaceholder, onfocus = "if (this.value == '" + Resources.ContactUs.Contact.MessagePlaceholder + "') this.value = '';", onblur = "if (this.value == '') { this.value = '" + @Resources.ContactUs.Contact.MessagePlaceholder + "'; }" })
                @Html.ValidationMessageFor(x => x.Message, null, new { @class = "validate" })
            </div>
            <div class="form-group mb-0">
                <button type="submit" class="btn btn-w3layouts btn-block  bg-theme text-white w-100 font-weight-bold text-uppercase" data-blast="bgColor">
                    @Resources.ContactUs.Contact.Send
                </button>
            </div>
        }
</div>

Wildlife/Views/ContactUs/ContactResult.cshtml
@model DeveloperWeb.Models.Contact
<!-- contact -->
<div class="contact s5" id="contactdiv">
    <div class="wrap">
        <div class="contact-left">
            <h3>@Resources.ContactUs.ContactResult.head</h3>
            <p class="style">@Resources.ContactUs.ContactResult.text1</p>
            <div class="get-intouch-left-address">
                <p>@Resources.ContactUs.ContactResult.p1</p>
                <p>@Resources.ContactUs.ContactResult.p2</p>
                
                <p class="style1">@Resources.ContactUs.ContactResult.email</p>
                <p class="style2">@Resources.ContactUs.ContactResult.phone</p>
            </div>
        </div>
        <div class="contact-right">
                @if (Utils.TempData("Status", TempData) == "emailSent")
                {
                    <div class="get-intouch-left-address"><p class="style1">@Resources.ContactUs.Contact.EmailSent</p><br/></div>
                }

                @{
                    var optionsGet = new AjaxOptions()
                    {
                        HttpMethod = "Get",
                        InsertionMode = InsertionMode.ReplaceWith,
                        UpdateTargetId = "contactdiv"
                    };
                }
                @Ajax.ActionLink(Resources.ContactUs.Contact.Reload, "ContactAjax", "", optionsGet, new { @class = "button1" })
        </div>
        <div class="clear"></div>
    </div>
</div>

Wildlife/Views/ContactUs/Index.cshtml
<!-- contact -->
<section class="contact-wthree py-sm-5 py-4" id="contact">
    <div class="container pt-lg-5">
        <div class="title-desc text-center pb-sm-3">
            <h3 class="main-title-w3pvt">contact us</h3>
            <p>Helping animals & working on environmental issues.</p>
        </div>
        <div class="row mt-4">
            <div class="col-lg-5 text-center">
                <h5 class="cont-form" data-blast="color">get in touch</h5>
                <div class="row flex-column">
                    <div class="contact-w3">
                        <span class="fa fa-envelope-open  mb-3" data-blast="color"></span>
                        <div class="d-flex flex-column">
                            <a href="mailto:example@email.com" class="d-block">info@example1.com</a>
                        </div>
                    </div>
                    <div class="contact-w3 my-4">
                        <span class="fa fa-phone mb-3" data-blast="color"></span>
                        <div class="d-flex flex-column">
                            <p class="my-1">+456 123 7890</p>
                        </div>
                    </div>
                    <div class="contact-w3">
                        <span class="fa fa-home mb-3" data-blast="color"></span>
                        <address>71 Pilgrim Avenue <br>44 Shirley Ave.<br> Goldfield Rd. Broome St, Newyork.</address>
                    </div>
                </div>

            </div>
            <div class="col-lg-7">
                <h5 class="cont-form" data-blast="color">contact form</h5>
                @Html.Action("ContactAjax", "ContactUs")
            </div>
        </div>
        <div class="mx-auto text-center mt-lg-0 mt-4">
            <iframe class="mt-lg-4 contact-form-wthreelayouts" data-blast="borderColor" src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d387190.2798902705!2d-74.25986790365911!3d40.697670067823786!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x89c24fa5d33f083b%3A0xc80b8f06e177fe62!2sNew+York%2C+NY%2C+USA!5e0!3m2!1sen!2sin!4v1536917325197" allowfullscreen></iframe>
            <!-- //footer right -->
        </div>
    </div>

</section>
<!-- //contact -->

Wildlife/Views/Home/About.cshtml
<!--  about -->
<section class="wthree-slide-btm pt-lg-5" id="about">
    <div class="container pt-sm-5 pt-4">
        <div class="row no-gutters">
            <div class="col-lg-5">
                <div class="slide-banner">
                </div>
            </div>
            <div class="col-lg-7">
                <div class="bg-abt light-bg">
                    <div class="container">
                        <div class="title-desc  pb-sm-3">
                            <h4 class="main-title-w3pvt">@Resources.Home.About.box1_title</h4>
                            <p>@Resources.Home.About.box1_desc</p>
                        </div>
                        <div class="row flex-column mt-lg-4 mt-3">
                            <div class="abt-grid">
                                <div class="row">
                                    <div class="col-sm-3">
                                        <div class="abt-icon" data-blast="bgColor">
                                            <span class="fa fa-ravelry"></span>
                                        </div>
                                    </div>
                                    <div class="col-sm-9 pl-sm-0">
                                        <div class="abt-txt ml-sm-0">
                                            <h4>sanctus takimata </h4>
                                            <p>
                                                Lo sea takimata sanctus est Lorem ipolor sit amet, no sea takimata
                                                sanctus est Loremsum dolor sit amet.
                                            </p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="abt-grid mt-4 pt-lg-2">
                                <div class="row">
                                    <div class="col-sm-3">
                                        <div class="abt-icon" data-blast="bgColor">
                                            <span class="fa fa-laptop"></span>
                                        </div>
                                    </div>
                                    <div class="col-sm-9 pl-sm-0">
                                        <div class="abt-txt ml-sm-0">
                                            <h4>takimata sanctus</h4>
                                            <p>
                                                Lo sea takimata sanctus est Lorem ipsum dolorsita.Lorem ipsum dolor
                                                sit amet,sed diam nonumy eirmod tempor invidunt ut labore et dolore
                                                magna aliquyam erat, At vero eos et accusam et justo duo dolores et
                                                ea
                                                rebum. Lorem ipsum dolor sit amet, no sea takimata sanctus est
                                                Lorem
                                                ipsum dolor sit amet. Stet clita kasd gubergren.
                                            </p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- //about -->
<!--  about bottom -->
<section class="wthree-slide-btm pb-lg-5">
    <div class="container pb-md-5 pb-4">
        <div class="row flex-row-reverse no-gutters">
            <div class="col-lg-5">
                <div class="ab-banner">
                </div>
            </div>
            <div class="col-lg-7">
                <div class="bg-abt">
                    <div class="container">
                        <div class="title-desc  pb-sm-3">
                            <h4 class="main-title-w3pvt">@Resources.Home.About.box2_title</h4>
                            <p>@Resources.Home.About.box2_desc</p>
                        </div>
                        <div class="row flex-column mt-lg-4 mt-3">
                            <div class="abt-grid">
                                <div class="row">
                                    <div class="col-sm-3">
                                        <div class="abt-icon" data-blast="bgColor">
                                            <span class="fa fa-ravelry"></span>
                                        </div>
                                    </div>
                                    <div class="col-sm-9 pl-sm-0">
                                        <div class="abt-txt ml-sm-0">
                                            <h4>sanctus takimata </h4>
                                            <p>
                                                Lo sea takimata sanctus est Lorem ipolor sit amet, no sea takimata
                                                sanctus est Loremsum dolor sit amet.
                                            </p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="abt-grid mt-4 pt-lg-2">
                                <div class="row">
                                    <div class="col-sm-3">
                                        <div class="abt-icon" data-blast="bgColor">
                                            <span class="fa fa-laptop"></span>
                                        </div>
                                    </div>
                                    <div class="col-sm-9 pl-sm-0">
                                        <div class="abt-txt ml-sm-0">
                                            <h4>takimata sanctus</h4>
                                            <p>
                                                Lo sea takimata sanctus est Lorem ipsum dolorsita.Lorem ipsum dolor
                                                sit amet,sed diam nonumy eirmod tempor invidunt ut labore et dolore
                                                magna aliquyam erat, At vero eos et accusam et justo duo dolores et
                                                ea
                                                rebum. Lorem ipsum dolor sit amet, no sea takimata sanctus est
                                                Lorem
                                                ipsum dolor sit amet. Stet clita kasd gubergren.
                                            </p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- //about boottom -->

Wildlife/Views/Home/Blog.cshtml
<!-- blog -->
<section class="blog_w3ls pb-lg-5 pb-4" id="posts">
    <div class="container py-sm-5 py-4">
        <div class="title-desc text-center pb-sm-3 mb-lg-5">
            <h3 class="main-title-w3pvt">recent blog</h3>
            <p>Helping animals & working on environmental issues.</p>
        </div>
        <div class="row mt-4">
            <!-- blog grid -->
            <div class="col-lg-4 col-md-6 mt-sm-0 mt-4">
                <div class="card">
                    <div class="card-header p-0 position-relative">
                        <a href="#exampleModal2" data-toggle="modal" aria-pressed="false" data-target="#exampleModal2"
                           role="button">
                            <img class="card-img-bottom" src="~/Assets/images/g1.jpg" alt="Card image cap">
                            <span class="fa fa-user post-icon bg-theme" aria-hidden="true" data-blast="bgColor"></span>

                        </a>
                    </div>
                    <div class="card-body">
                        <h5 class="blog-title card-title font-weight-bold">
                            <a href="#exampleModal2" data-toggle="modal" aria-pressed="false" data-target="#exampleModal2"
                               role="button">Cras ultricies ligula sed.</a>
                        </h5>
                        <p>
                            At vero eos et accusam et justo duo dolores et ea rebum. Lorem ipsum dolor sit
                            ametLorem ipsum dolor sit amet,sed diam nonumy.
                        </p>
                        <label class="mt-2"> <span class="fa fa-calendar mr-3"></span>08.10.2018</label>
                        <button type="button" class="btn blog-btn wthree-bnr-btn" data-toggle="modal" aria-pressed="false"
                                data-target="#exampleModal2">
                            Read more
                        </button>
                    </div>
                </div>
            </div>
            <!-- //blog grid -->
            <!-- blog grid -->
            <div class="col-lg-4 col-md-6 mt-md-0 mt-sm-5 mt-4">
                <div class="card">
                    <div class="card-header p-0 position-relative">
                        <a href="#exampleModal3" data-toggle="modal" aria-pressed="false" data-target="#exampleModal3"
                           role="button">
                            <img class="card-img-bottom" src="~/Assets/images/g2.jpg" alt="Card image cap">
                            <span class="fa fa-user post-icon bg-theme" aria-hidden="true" data-blast="bgColor"></span>
                        </a>
                    </div>
                    <div class="card-body">
                        <h5 class="blog-title card-title font-weight-bold">
                            <a href="#exampleModal3" data-toggle="modal" aria-pressed="false" data-target="#exampleModal3"
                               role="button">magna porta auris.</a>
                        </h5>
                        <p>
                            At vero eos et accusam et justo duo dolores et ea rebum. Lorem ipsum dolor sit
                            ametLorem ipsum dolor sit amet,sed diam nonumy.
                        </p>
                        <label class="mt-2"> <span class="fa fa-calendar mr-3"></span>02.11.2018</label>
                        <button type="button" class="btn blog-btn wthree-bnr-btn" data-toggle="modal" aria-pressed="false"
                                data-target="#exampleModal3">
                            Read more
                        </button>
                    </div>
                </div>
            </div>
            <!-- //blog grid -->
            <!-- blog grid -->
            <div class="col-lg-4 col-md-6 mt-lg-0 mt-4 mx-auto">
                <div class="card">
                    <div class="card-header p-0  position-relative">
                        <a href="#exampleModal4" data-toggle="modal" aria-pressed="false" data-target="#exampleModal4"
                           role="button">
                            <img class="card-img-bottom" src="~/Assets/images/g3.jpg" alt="Card image cap">
                            <span class="fa fa-user post-icon bg-theme" aria-hidden="true" data-blast="bgColor"></span>
                        </a>
                    </div>
                    <div class="card-body">
                        <h5 class="blog-title card-title font-weight-bold">
                            <a href="#exampleModal4" data-toggle="modal" aria-pressed="false" data-target="#exampleModal4"
                               role="button">Cras ultricies ligula sed.</a>
                        </h5>
                        <p>
                            At vero eos et accusam et justo duo dolores et ea rebum. Lorem ipsum dolor sit
                            ametLorem ipsum dolor sit amet,sed diam nonumy.
                        </p>
                        <label class="mt-2"> <span class="fa fa-calendar mr-3"></span>10.11.2018</label>
                        <button type="button" class="btn blog-btn wthree-bnr-btn" data-toggle="modal" aria-pressed="false"
                                data-target="#exampleModal4">
                            Read more
                        </button>
                    </div>
                </div>
            </div>
            <!-- //blog grid -->
        </div>
    </div>
</section>
<!-- //blog -->

Wildlife/Views/Home/BlogModal.cshtml
<!-- blog modal1 -->
<div class="modal fade" id="exampleModal2" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel2"
     aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header bg-theme">
                <h5 class="modal-title" id="exampleModalLabel2">Cras ultricies ligula sed.</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body text-center">
                <img src="~/Assets/images/g1.jpg" class="img-fluid" alt="" />
                <p class="text-left my-4">
                    Quisque velit nisi, pretium ut lacinia in, elementum id enim. Curabitur non nulla sit amet
                    nisl
                    tempus convallis quis ac
                    lectus. Cras ultricies ligula sed magna dictum porta.
                </p>
            </div>
        </div>
    </div>
</div>
<!-- //blog modal1 -->
<!-- blog modal2 -->
<div class="modal fade" id="exampleModal3" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel3"
     aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header bg-theme">
                <h5 class="modal-title" id="exampleModalLabel3">Cras ultricies ligula sed.</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body text-center">
                <img src="~/Assets/images/g2.jpg" class="img-fluid" alt="" />
                <p class="text-left my-4">
                    Quisque velit nisi, pretium ut lacinia in, elementum id enim. Curabitur non nulla sit amet
                    nisl
                    tempus convallis quis ac
                    lectus. Cras ultricies ligula sed magna dictum porta.
                </p>
            </div>
        </div>
    </div>
</div>
<!-- //blog modal2 -->
<!-- blog modal3 -->
<div class="modal fade" id="exampleModal4" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel4"
     aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header bg-theme">
                <h5 class="modal-title" id="exampleModalLabel4">Cras ultricies ligula sed magna.</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body text-center">
                <img src="~/Assets/images/g3.jpg" class="img-fluid" alt="" />
                <p class="text-left my-4">
                    Quisque velit nisi, pretium ut lacinia in, elementum id enim. Curabitur non nulla sit amet
                    nisl
                    tempus convallis quis ac
                    lectus. Cras ultricies ligula sed magna dictum porta.
                </p>
            </div>
        </div>
    </div>
</div>
<!-- //blog modal3-->

Wildlife/Views/Home/Index.cshtml
@Html.Partial("About")
@Html.Partial("Stats")
@Html.Partial("Services")
@Html.Partial("SlideDonations")
@Html.Partial("Pricing")
@Html.Partial("Team")
@Html.Partial("Portfolio")
@Html.Partial("Testimonials")
@Html.Partial("Blog")
@Html.Action("Index", "ContactUs")

Wildlife/Views/Home/SlideDonations.cshtml
    <!-- slide -->
<div class="abt_bottom py-lg-5 bg-theme" data-blast="bgColor">
    <div class="container py-sm-4 py-3">
        <h4 class="abt-text text-capitalize text-sm-center">
            Over 70% of donations made to us directly impact animals
            in the wild
        </h4>
        <div class="d-sm-flex justify-content-center">
            <a class="btn light-bg mt-4 w3_pvt-link-bnr scroll bg-theme1" href="#contact" role="button">
                contact
                us
            </a>
            <a href="#" role="button" data-toggle="modal" data-target="#exampleModal1" class="btn light-bg mt-4 ml-sm-3 w3_pvt-link-bnr">
                make a contribution
            </a>
        </div>
    </div>
</div>
<!-- //slide -->